development:
  adapter: postgresql
  encoding: unicode
  database: hackathon
  pool: 5
  username: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: hackathon_test
  pool: 5
  username: postgres
  host: localhost
